export const NOTFOUND_UPDATE_STATE = 'NOTFOUND_UPDATE_STATE'
export const NOTFOUND_RESET_STATE = 'NOTFOUND_RESET_STATE'
export const TEST_UPDATE_STATE = 'TEST_UPDATE_STATE'
export const TEST_RESET_STATE = 'TEST_RESET_STATE'
export const HOME_UPDATE_STATE = 'HOME_UPDATE_STATE'
export const HOME_RESET_STATE = 'HOME_RESET_STATE'
//${const}
 						