export const NOTFOUND_UPDATE_STATE = 'NOTFOUND_UPDATE_STATE'
export const NOTFOUND_RESET_STATE = 'NOTFOUND_RESET_STATE'
export const TEST_UPDATE_STATE = 'TEST_UPDATE_STATE'
export const TEST_RESET_STATE = 'TEST_RESET_STATE'
export const GUIDELINE_UPDATE_STATE = 'GUIDELINE_UPDATE_STATE'
export const GUIDELINE_RESET_STATE = 'GUIDELINE_RESET_STATE'
//${const}
 						